# Generated by Django 3.0.7 on 2020-06-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='slugName',
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
