# Generated by Django 3.0.7 on 2020-06-27 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_customer_slugname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='slugName',
        ),
    ]
