# Generated by Django 3.0.7 on 2020-06-14 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_slider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='telephone',
        ),
        migrations.AddField(
            model_name='course',
            name='generateDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
