# Generated by Django 3.0.7 on 2020-06-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_auto_20200614_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='reservation',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
