# Generated by Django 3.0.7 on 2020-06-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_auto_20200614_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='endDate',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='startDate',
            field=models.CharField(max_length=50),
        ),
    ]
