# Generated by Django 3.0.7 on 2020-06-14 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_auto_20200614_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='generateDate',
        ),
    ]
