# Generated by Django 3.0.7 on 2020-06-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_remove_course_generatedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='reservation',
        ),
        migrations.RemoveField(
            model_name='course',
            name='status',
        ),
        migrations.AlterField(
            model_name='course',
            name='endDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='startDate',
            field=models.DateTimeField(),
        ),
    ]
