# Generated by Django 3.0.7 on 2020-06-14 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_auto_20200614_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
    ]
