# Generated by Django 3.0.7 on 2020-06-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_auto_20200614_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='pic',
        ),
        migrations.AlterField(
            model_name='course',
            name='endDate',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='startDate',
            field=models.CharField(max_length=50),
        ),
    ]
