# Generated by Django 3.0.7 on 2020-06-14 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0009_auto_20200614_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel.Branch'),
        ),
        migrations.AddField(
            model_name='course',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='course',
            name='reservation',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel.Teacher'),
        ),
        migrations.AlterField(
            model_name='course',
            name='endDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='startDate',
            field=models.DateTimeField(),
        ),
    ]
