# Generated by Django 3.0.7 on 2020-06-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_auto_20200614_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='generateDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
