# Generated by Django 3.0.7 on 2020-06-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0011_course_generatedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='endDate',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='startDate',
            field=models.CharField(max_length=50),
        ),
    ]
