# Generated by Django 3.0.7 on 2020-06-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0012_auto_20200614_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='fee',
            field=models.IntegerField(),
        ),
    ]
