# Generated by Django 3.0.7 on 2020-06-14 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0013_auto_20200614_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='course',
            name='endDate',
        ),
        migrations.RemoveField(
            model_name='course',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='course',
            name='generateDate',
        ),
        migrations.RemoveField(
            model_name='course',
            name='introduction',
        ),
        migrations.RemoveField(
            model_name='course',
            name='place',
        ),
        migrations.RemoveField(
            model_name='course',
            name='reservation',
        ),
        migrations.RemoveField(
            model_name='course',
            name='startDate',
        ),
        migrations.RemoveField(
            model_name='course',
            name='status',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title',
        ),
    ]
