# Generated by Django 3.0.7 on 2020-06-14 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0014_auto_20200614_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='pic',
        ),
    ]
