# Generated by Django 3.0.7 on 2020-06-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0015_remove_course_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.AddField(
            model_name='course',
            name='branchh',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
