# Generated by Django 3.0.7 on 2020-06-14 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0016_auto_20200614_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('introduction', models.CharField(max_length=500)),
                ('startDate', models.CharField(max_length=50)),
                ('endDate', models.CharField(max_length=50)),
                ('generateDate', models.CharField(max_length=50)),
                ('fee', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('reservation', models.IntegerField(blank=True, default=0, null=True)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel.Branch')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel.Teacher')),
            ],
        ),
    ]
