# Generated by Django 3.0.7 on 2020-06-14 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0017_courses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='generateDate',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='reservation',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='status',
        ),
    ]
