# Generated by Django 3.0.7 on 2020-06-14 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0020_auto_20200614_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.Branch'),
        ),
        migrations.RemoveField(
            model_name='courses',
            name='teacher',
        ),
        migrations.AddField(
            model_name='courses',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.Teacher'),
        ),
    ]
