# Generated by Django 3.0.7 on 2020-06-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0022_auto_20200614_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='endDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Date (mm/dd/2020)'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='startDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Date (mm/dd/2020)'),
        ),
    ]
