# Generated by Django 3.0.7 on 2020-06-15 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0027_courses_createdat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
