# Generated by Django 3.0.7 on 2020-06-15 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0028_delete_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='courseName',
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.Courses'),
        ),
    ]
