# Generated by Django 3.0.7 on 2020-06-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0029_auto_20200615_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Active ?'),
        ),
    ]
