# Generated by Django 3.0.7 on 2020-06-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0031_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='ip',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
