# Generated by Django 3.0.7 on 2020-06-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0032_admins_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='Country',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
