# Generated by Django 3.0.7 on 2020-06-20 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0033_admins_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admins',
            old_name='Country',
            new_name='country',
        ),
    ]
