# Generated by Django 3.0.7 on 2020-06-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0035_cronlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='slugName',
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
