# Generated by Django 3.1.12 on 2022-12-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0037_auto_20210630_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ate', models.DateTimeField(auto_now_add=True)),
                ('fee', models.IntegerField()),
                ('position', models.CharField(blank=True, choices=[('cleaener', 'Cleaner'), ('washer', 'washer'), ('security', 'security')], max_length=200, null=True)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Select an image file')),
                ('status', models.BooleanField(default=True, verbose_name='Active ?')),
            ],
        ),
    ]
