# Generated by Django 3.1.12 on 2024-01-29 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0038_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentsRepository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('shipment_notification', 'Kargo Barkodu Oluştur Popup İçeriği')], max_length=120, verbose_name='Adı')),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='import', verbose_name='File')),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Adı')),
                ('url', models.URLField(max_length=255, verbose_name='Link')),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AddField(
            model_name='documentsrepository',
            name='files',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.files', verbose_name='Dosyalar'),
        ),
        migrations.AddField(
            model_name='documentsrepository',
            name='links',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.links', verbose_name='Linkler'),
        ),
    ]
