# Generated by Django 3.1.12 on 2024-01-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0040_auto_20240130_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Tipi'),
        ),
    ]
