# Generated by Django 3.1.12 on 2024-01-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0041_auto_20240130_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsrepository',
            name='name',
            field=models.CharField(choices=[('shipment_notification', 'Kargo Barkodu Oluştur Popup İçeriği')], max_length=120, unique=True, verbose_name='Adı'),
        ),
    ]
